import 'package:code_challenge/domain/domain.dart';

List<Absence> mockAbsences = [
    Absence(
      userId: 1,
      type: 'vacation',
      startDate: '2024-05-01',
      endDate: '2024-05-05',
      memberNote: 'Enjoying the vacation',
      admitterNote: 'Approved',
      status: AbsenceRequestStatus.confirmed,
      createdAt: '2024-05-01',
      crewId: 1,
      id: 1,
      memberName: 'John Doe',
      memberImage: 'http://example.com/image1.jpg',
    ),
    Absence(
      userId: 2,
      type: 'sickness',
      startDate: '2024-05-06',
      endDate: '2024-05-08',
      memberNote: 'Feeling unwell',
      admitterNote: 'Pending approval',
      status: AbsenceRequestStatus.requested,
      createdAt: '2024-05-06',
      crewId: 2,
      id: 2,
      memberName: 'Jane Smith',
      memberImage: 'http://example.com/image2.jpg',
    ),
    Absence(
      userId: 3,
      type: 'vacation',
      startDate: '2024-05-10',
      endDate: '2024-05-12',
      memberNote: 'Family trip',
      admitterNote: 'Approved',
      status: AbsenceRequestStatus.confirmed,
      createdAt: '2024-05-10',
      crewId: 3,
      id: 3,
      memberName: 'Alice Johnson',
      memberImage: 'http://example.com/image3.jpg',
    ),
  ];