name: code_challenge
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.4
  bloc_test: ^10.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/json_files/